language: java
install: mvn install -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
script: mvn package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
deploy:
  provider: releases
  api_key:
    secure: XqVfGi6CVDo2xIJJ4N2fMtDUuaH5Zhk381mRKCaC+yKpzF9fEUVgthIqmRWzLeskNx1nsLMgVz5YlTqmxTZvmHHsbt8fDZj55hVTmFJn8d+/79P/I9Nh6MJL5+5gJvGCk2gjU7VyPQr/Xg1Pxb5IJfNswuPOCuWSto8ZjaFDRSETXwFFnLGdIv0w5JgZMQq2AOG/jPgfmY1xPjsbMoUB2mgG8NDcuZMSRKmhFFczRpYBG1PCvhM4uvnkaRWFyasPqKLI9Kz/Mrehk+nS8EHwS7/5DVSfsOV8zT0tK4m08p9eYo7TA/WHcbeKjciqaiHzFx2Mo3MhFEPC1XIQ36ZUJXUTi/eB5ZhzQSsSpIVPkEgWq6U3ELZck1ZFAv48w8sjupL0/FbRezCKS37A7HnKWaROAHA/4QksR3VkqCcHDw416FST0+2h0QX+yst1aWJfxLrz7y1AM0tm1RWYQLJi3jn+uTfuojpw+TWug65cHrbgWllC4CU41pPjSpMwgqtximYLSEacDjBwtxxmSrPjz3I5P06HEZ1pLkRddTwI4FI3AsSNhuo+JRF1WEUwVzCUjVLwn2SJtblzFfoTJYGnl9ZeHFy0nsTyXX6R6tvAck+4tJpA3zZc9NAmNIWaH8t9MUj+9Zi3Ggl7jvqOyyIJoSbNPv3ttESkyl0okt0YZzg=
  file: 'CHANGELOG.md'
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - SONATYPE_USERNAME=lymanrb
  - secure: SxuF4re32f2ubtQwGyh3Vhanmk5uc90EarBVO8R1R5R6TuD5RIe0uOih9IY8RQ7uZagYD7aWC90UEctnwxWL96HdD3Hja2nSHHFtnQG/lTpv9NWpEt4S3sKw5mrqSvHphh5tV55fqgUun6IIk0b8ngrTYCmPIUkP4/gn2sAO0BAAkbcSUFWAJq5P98uBoSV805MFxzdsWexixwuF5xqM2TUjh5kpVHmMQ/1J608ti4d48boFYnkrR3TZk0kO2Ajga2ccTGPygvClx67D0X5/2DsolBw5huzFh+6okrVfh43DD8bYNso3hwqYLyAxhUgAEklDxC8JPPSoepi5+8Irg2sSchGF/lRp9jkdJ0pS+Z0Gv3OCQU6B6sX1299SDfKA+8ZE2uU8shHCwrrpSanJzDiLi3Jg89UL9fdaLcAhBCPcZT3xQHhMFqQPdp6WyYQrFhXZN/ngWdk+HKdASgxhK5URuRE1akkNP8Im3PjgNhdnmQ9j4jlw348HhGju9zmtQxzjfpx0k0CxI3FRwW72e4ND5Jn4h1v5cPN9rxuQxMXeYCXRjnTlO3odqhLWtEtSXU/MncIH+P/XqJ0lDJMZPZfHjwYMVMzDRmfUrMmRC4kNgPShm6jgAdhkh3vYSllHVFW04ASxYP5C7ersXGmX75K+/SjfXodGFJ5dUs4GZgU=
  - secure: QC/lToqLXFqKFYwcPdL2MryeSm8vdzCVLn4RqLTImQs2FRupB2lHDC1nQMnTDQlb/3UA3fnxms0hdU9JOdIwqQ6CxvuwPeylMzsRNn75o+X2GtO49tgZkhONTpxYjxtBueFaZtclE3U3ggzaE/kPqDncYGKzEBAfjrIRi8DM5sHwdkq8OBUR06ofIp/UOCSXqGGWNeUz4r5J1CJyARdFag+YEwGZbY0sr4YTXg3SOE+N5wx9B5pa8fsjoyLGCuEo4A+3cfJwZvvj1mM2nkubaOxqDFRlIRTtUUlJdHTnLU+E1bkTHQ0QVFJBDTV0WsGbsMV/MpXifOhaq75SdEyXNUeOUwM+pitbHC1uEzwGAh5O77/TNZsSZDoEgoBhWTO5fLGD0/ngUGQ9/Dch+H98lZ1fF2heM5Z4HKDEUpmgkKm9VbTsKI5zAgRKWjZM8fSuG/+FNq35JbzyoJRzQQUocjeRov1J5xhMXKFdTTdxfGpaqtxgYymrejq8icgM5Vx88ws47oYZBTAI3B1bZLqrQ8+MmtljZHI70DDwx/f1L5Yz41USHxZix/pqmuBpoq3KiPTnIPg0SAss1mg5M9xxDts4RqBDecL5WCSc9kW4pLNvtJ5ci1we+SWgWLH94YO4YfFgJKYQ90WiakFXQrwSqMVYLCHW4kx+3lpYgEDlyy8=
after_deploy:
- echo "deploying to maven central"
- gpg --import secret.key.asc
- mvn deploy --settings settings.xml -DskipTests=true -Dgpg.passphrase=$GPG_PASSPHRASE
before_install:
- openssl aes-256-cbc -K $encrypted_f86dc6d297df_key -iv $encrypted_f86dc6d297df_iv
  -in secret.key.asc.enc -out secret.key.asc -d
